name: Deploy Angular App to Linux Server

on:
  push:
    branches:
      - main  # or 'master' or any branch you deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Install dependencies and build Angular app
      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration production

      # 4️⃣ Prepare deployment artifact
      - name: Archive production files
        run: |
          cd dist
          tar -czf ../app-dist.tar.gz ./*
          cd ..

      # 5️⃣ Deploy to Linux server via SSH
      - name: Deploy to Linux server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST_PROD }}
          username: ${{ secrets.SSH_USER_PROD }}
          key: ${{ secrets.SSH_KEY_PROD }}
          source: "app-dist.tar.gz"
          target: "/tmp/"

      # 6️⃣ Extract and move files on server
      - name: Extract and move files on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST_PROD }}
          username: ${{ secrets.SSH_USER_PROD }}
          key: ${{ secrets.SSH_KEY_PROD }}
          script: |
            mkdir -p "/var/www/html"
            tar -xzf /tmp/app-dist.tar.gz -C "/var/www/html" --strip-components=1
            rm /tmp/app-dist.tar.gz
            sudo systemctl reload nginx